# configurable rules can be customized from this configuration file
# binary rules can set their severity level
excluded:
 - ThirdParty
 - Tools
 - Serenity
 - Frameworks
 - ecomove/LocalizedStrings/LocalizedStrings.swift
 - ecomove/LoggingReducer.swift
 - apple
 
force_cast: error # implicitly

force_try:
  severity: error # explicitly

line_length: 130

opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping
  - missing_docs
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_string
  - explicit_init
  - first_where
  - multiline_arguments
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_type_annotation
  - untyped_error_in_catch
  - inclusive_language
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
  
switch_case_alignment:
  indented_cases: true

function_parameter_count:
  warning: 10
  error: 20

identifier_name:
  max_length:
    warning: 50
    error: 1000
  excluded: # excluded via string array
    - QM
    - MIMEType
    - P
    - R
    - DEV
    - id
    - URL
    - Ok
    - vc
    - db
    - r
    - p

force_unwrapping: error

disabled_rules: # rule identifiers to exclude from running
 - line_length
 - file_length
 - type_body_length
 - type_name
 - nesting
 - function_body_length
 - redundant_optional_initialization
